import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/Theme/ThemeProvider'
import WebSocketConnector from '@/components/WebSocketConnector'
import { QueryClientProvider } from '@tanstack/react-query'
/* import getQueryClient from '@/lib/QueryClient' */
import { Provider } from '@radix-ui/react-toast'
/* import QueryProvider from './providers' */

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

/* const getVoip = localFont({
	src: '../../public/GetVoIPGrotesque/GetVoIPGrotesque.ttf',
	variable: '--font-getvoip',
}) */

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='ru'
			suppressHydrationWarning
			className={`${geistSans.variable} ${geistMono.variable}`}
		>
			<body className='antialiased'>
				<ThemeProvider>
					{/* <QueryProvider> */}
					{children}
					{/* </QueryProvider> */}
					<WebSocketConnector />
				</ThemeProvider>
			</body>
		</html>
	)
}
